version: '3.8'

services:
    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        ports:
            - '5432:5432'

    backend:
        build:
            context: ./backend
        container_name: django-backend
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend:/app
        ports:
            - '8000:8000'
        env_file:
            - .env
        depends_on:
            - db

    frontend:
        build:
            context: ./frontend
        container_name: react-frontend
        volumes:
            - ./frontend:/app
        ports:
            - '3000:3000'
        environment:
            - CHOKIDAR_USEPOLLING=true # 리눅스 환경에서 핫 리로딩 설정

volumes:
    postgres_data:
